# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(41000d7b-45d9-4f30-aa8c-1f1b3e657eab)'
    appType: 'webApp'
    WebAppName: 'met-project'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
